/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kanedog (https://sketchfab.com/Kane33)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/imac-24-m1-green-2021-0cfe04fb7123492ab96664877607333f
Title: iMac 24" M1 Green (2021)
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import { gsap } from 'gsap'
const DemoComputer = (props) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/imac.glb')

  const txt = useVideoTexture(props.texture ? props.texture : '/textures/project/project1.mp4')

  useEffect(() => {
    if (txt) {
      txt.flipY = false
      txt.center.set(0.5, 0.5)
      txt.rotation = Math.PI
      txt.repeat.x = -1
      txt.needsUpdate = true
    }
  }, [txt])

  useGSAP(() => {
    gsap.from(group.current.rotation, { y: Math.PI * 2, duration: 1, ease: 'power3.out' })
  }, [txt])

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Glass_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.SVvlQFeQaCVtSFx_vray_brown_0.geometry} material={materials.vray_brown} />
      <mesh geometry={nodes.jsgSSsFWnPVuvlo_vray_gradient_grey_0.geometry} material={materials.vray_gradient_grey} />
      <mesh geometry={nodes.bXhfAiclTGoEHtf_vray_green_light_0.geometry} material={materials.vray_green_light} />
      <mesh geometry={nodes.REOuBrSIhooKFvE_vray_grey_light_0.geometry} material={materials.vray_grey_light} />
      <mesh geometry={nodes.oLzqSmuqpmfRAfx_vray_green_bright_0.geometry} material={materials.vray_green_bright} />
      <mesh geometry={nodes['UEgtAKJkuvgHVPd_vray_circular-brushed-aluminium_0'].geometry} material={materials['vray_circular-brushed-aluminium']} />
      <mesh geometry={nodes.UBCQiSKpEUGzJFK_vray_grey_light_0.geometry} material={materials.vray_grey_light} />
      <mesh geometry={nodes.IWbaYtOlBzSNIyq_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.zlOUeiGttqhGIQz_vray_green2_0.geometry} material={materials.vray_green2} />
      <mesh geometry={nodes.CkHCIOhXhGBCiBm_vray_green4_0.geometry} material={materials.vray_green4} />
      <mesh geometry={nodes.TmMtsrYsHIzBtZK_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.dTftzVqzNmjgiyE_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.pRMrIGLANuLhYKK_vray_green_light_0.geometry} material={materials.vray_green_light} />
      <mesh geometry={nodes.phdMEqggLqWOXid_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.MOWfSejhnaQmBMC_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.xqMubHUGCNIjgCO_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.ncfgXaUljSFPlBY_vray_grey_light_0.geometry} material={materials.vray_grey_light} />
      <mesh geometry={nodes.gNConWuPWDuZWap_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.CBdGjQnOwJBbnSQ_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.jOeYCrYIgLwBEEx_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.gtkJFuBfDnRqZMd_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes['SLbIPZxIcDbAlJS_vray_power-cord_0'].geometry} material={materials['vray_power-cord']} />
      <mesh geometry={nodes['zcoicRAlpvuSrKr_vray_dark-green_0'].geometry} material={materials['vray_dark-green']} />
      <mesh geometry={nodes.jyYtUDaBiTcowni_vray_gradient_grey_0.geometry} material={materials.vray_gradient_grey} />
      <mesh geometry={nodes.XSdhNZdXwSNqPRJ_vray_green3_0.geometry} material={materials.vray_green3} />
      <mesh geometry={nodes.bIufPvKSDrquPrX_vray_green_light_0.geometry} material={materials.vray_green_light} />
      <mesh geometry={nodes.iMac24_stand_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.dPvFywXtHXZhqUE_vray_green2_0.geometry} material={materials.vray_green2} />
      <mesh geometry={nodes.aDIZpalhgNEzaje_vray_grey_light_0.geometry} material={materials.vray_grey_light} />
      <mesh geometry={nodes['gyzKGCzhZOvLETT_vray_circular-brushed-aluminium_0'].geometry} material={materials['vray_circular-brushed-aluminium']} />
      <mesh geometry={nodes.mQHMDWriMmDJmYd_vray_green_light_0.geometry} material={materials.vray_green_light} />
      <mesh geometry={nodes.LduomgHjimaRhFJ_vray_green2_0.geometry} material={materials.vray_green2} />
      <mesh geometry={nodes.LSlhNZEQpdgfieG_vray_grey_light_0.geometry} material={materials.vray_grey_light} />
      <mesh geometry={nodes.JTxUjaHIyDdmBDZ_vray_green_light_0.geometry} material={materials.vray_green_light} />
      <mesh geometry={nodes.wfWsZSDwCYKEFok_vray_grey_light_0.geometry} material={materials.vray_grey_light} />
      <mesh geometry={nodes.GuzlKwLwYEozbej_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.CkdMCtaFcotYYna_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.CASjyMtTXQNuKhv_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.MbyeoqNrsjXusii_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.RXUnhzdBWSBnvAg_vray_grey_light_0.geometry} material={materials.vray_grey_light} />
      <mesh geometry={nodes.TXFkpraIorKIfcW_vray_green2_0.geometry} material={materials.vray_green2} />
      <mesh geometry={nodes.TywyWrFfETHXCIl_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.UJIfgKXaaFAejuW_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.WMqFzEWkSsTslxA_vray_green1_0.geometry} material={materials.vray_green1} />
      <mesh geometry={nodes.ZEuipVKguqwgRLv_vray_gradient_grey_0.geometry} material={materials.vray_gradient_grey} />
      <mesh geometry={nodes.ayCiZofhiWvVrEF_vray_green_bright_0.geometry} material={materials.vray_green_bright} />
      <mesh geometry={nodes.eTXZtRORoUtZDCs_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.gveSzNFSnDnwZVP_vray_brown_0.geometry} material={materials.vray_brown} />
      <mesh geometry={nodes.jBIrfqRlUNCzYqX_vray_gradient_grey_0.geometry} material={materials.vray_gradient_grey} />
      <mesh geometry={nodes.kPZaEBVgsaHnoSL_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.kwkECikLrXukhHD_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.mKGFCAUnzxxoNUI_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes['saahvhnqbSNwhxw_vray_circular-brushed-aluminium_0'].geometry} material={materials['vray_circular-brushed-aluminium']} />
      <mesh geometry={nodes.tBoiCfHYFDKkNER_vray_green_light_0.geometry} material={materials.vray_green_light} />
      <mesh geometry={nodes.tDhVRJNEAPrvlCR_vray_green2_0.geometry} material={materials.vray_green2} />
      <mesh geometry={nodes.tbYNYdoFNBgixjV_vray_green2_0.geometry} material={materials.vray_green2} />
      <mesh geometry={nodes.vrKYMDMllykAvTZ_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.wIebFLVIiNTowDh_vray_green2_0.geometry} material={materials.vray_green2} />
      <mesh geometry={nodes.IpkUtuMMqwAGzXB_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.zTjkqrKCiQPliOH_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes['zDhURIdCYeZwYsD_vray_dark-green_0'].geometry} material={materials['vray_dark-green']} />
      <mesh geometry={nodes.vUTyUnDeiiJVdBj_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.tfMdBaQNVwFDjrh_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.tTeYxkrqNbGXZos_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.snDmhTduWwFwjqi_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.rdIoCcDSNcDiYBR_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.rVRACxZFaCSDuaM_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.rFdRGAQwvTYtwlh_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.qzEEXXIOFTerXbS_vray_green_dark_0.geometry} material={materials.vray_green_dark} />
      <mesh geometry={nodes.lQTPnlGNjFTlJcp_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.lLztMhLBoaFqxHa_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.lLErCugBsJXPsZA_vray_gradient_grey_0.geometry} material={materials.vray_gradient_grey} />
      <mesh geometry={nodes.kKewBUBeUvdHJJS_vray_green4_0.geometry} material={materials.vray_green4} />
      <mesh geometry={nodes.jxbYfWYoTZFQmEU_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.jAlUjOfuyAfCdlM_vray_white_0.geometry} material={materials.vray_white} />
      <mesh name="Retina_screen" geometry={nodes.Retina_screen_vray_screen_0.geometry} position={[0, 0, 9.889]}>
        <meshBasicMaterial map={txt} toneMapped={false} />
      </mesh>
      <mesh geometry={nodes.inMHYVIRkmKLPAd_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.iWQgjifNecoaZWs_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.fIhvyNDIgdiByvW_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.enEUrOvmHmPvDPW_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.djinFdwkCqUaicI_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.dhUWLbChAmZXycV_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.dBBVVHeaooaFWgT_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.cghYnlxhMkYAqBF_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.baiczUKOTtUhuco_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.atgbLLxiVwyqSXT_vray_grey_light_0.geometry} material={materials.vray_grey_light} />
      <mesh geometry={nodes.ZCnRoRRlOcIiNQg_vray_green1_0.geometry} material={materials.vray_green1} />
      <mesh geometry={nodes.YlVMcsvLMybImKi_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.YaZWTvFNCQNdAiw_vray_green_dark_0.geometry} material={materials.vray_green_dark} />
      <mesh geometry={nodes.YBeEwWBYANOWfKT_vray_green_dark_0.geometry} material={materials.vray_green_dark} />
      <mesh geometry={nodes.XvZrMzAaKesvFig_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.XhzJOCqrpGoKHNG_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.XUuyXONEzIOLfjB_vray_gradient_grey_0.geometry} material={materials.vray_gradient_grey} />
      <mesh geometry={nodes['XBVarRDKFDawGUB_vray_dark-green_0'].geometry} material={materials['vray_dark-green']} />
      <mesh geometry={nodes.WvsXDCbfkJPUMci_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.WvGQowZMQdanMNQ_vray_jade_0.geometry} material={materials.vray_jade} />
      <mesh geometry={nodes['TsqghoyxwLaLyhC_vray_dark-green_0'].geometry} material={materials['vray_dark-green']} />
      <mesh geometry={nodes.TUuQnyNMYNqOTHl_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.TLkWLtaldiGrMRM_vray_dark_gradient_0.geometry} material={materials.vray_dark_gradient} />
      <mesh geometry={nodes.TAttlfOXDLwKpba_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.SpQVvHhenuiXGiG_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.SRdmRAslwispVHt_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.SLZguuPHbCImGCt_vray_green_dark_0.geometry} material={materials.vray_green_dark} />
      <mesh geometry={nodes.SJpHMcTfTNlQDth_vray_green_dark_0.geometry} material={materials.vray_green_dark} />
      <mesh geometry={nodes.RYrPcvpkkVPKcwN_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.QtoBSMYHTRLRxrv_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.PttXbwlJEZMcdQT_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.PrrGqbSGhmESNCg_vray_gradient_grey_0.geometry} material={materials.vray_gradient_grey} />
      <mesh geometry={nodes.PqDhjzKFGPzIAHn_vray_grey_light_0.geometry} material={materials.vray_grey_light} />
      <mesh geometry={nodes.PZvDnxfPVbvzbIZ_vray_grey_light_0.geometry} material={materials.vray_grey_light} />
      <mesh geometry={nodes.OPMYkGxLHlklIIv_vray_green_dark_0.geometry} material={materials.vray_green_dark} />
      <mesh geometry={nodes.NGOGkvDkslscyDj_vray_green_dark_0.geometry} material={materials.vray_green_dark} />
      <mesh geometry={nodes.MRDByNQjaiOBoyi_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.KGdyDmqfcthwjjT_vray_dark_grey_0.geometry} material={materials.vray_dark_grey} />
      <mesh geometry={nodes.IEKwOKGFoeUNJKz_vray_jade_0.geometry} material={materials.vray_jade} />
      <mesh geometry={nodes.IDvZIJqJxYgFdzF_vray_gradient_grey_0.geometry} material={materials.vray_gradient_grey} />
      <mesh geometry={nodes.IBQkjODsHRkneRC_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.HrgHwMEELMqerwv_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.GmTTfJUqxAOkktU_vray_jade_0.geometry} material={materials.vray_jade} />
      <mesh geometry={nodes.GjktsTIKvdJvjTi_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.GhYfvEtiMJwocpf_vray_green_dark_0.geometry} material={materials.vray_green_dark} />
      <mesh geometry={nodes.FdPRcACRJAEWZpy_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes['FXEcInHWqYhBKgT_vray_dark-green_0'].geometry} material={materials['vray_dark-green']} />
      <mesh geometry={nodes.EjYShLihpkEUaza_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes.EgeziiQQEZZnNJM_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.EekiGOqwXKUOwzI_vray_blue_0.geometry} material={materials.vray_blue} />
      <mesh geometry={nodes.DipuIfRYazSguKT_vray_white_0.geometry} material={materials.vray_white} />
      <mesh geometry={nodes.CkkkMacLFvkEnLM_vray_green1_0.geometry} material={materials.vray_green1} />
      <mesh geometry={nodes.CHynENmzaFpAqqw_vray_Black_0.geometry} material={materials.vray_Black} />
      <mesh geometry={nodes['Back_drak-green_vray_dark-green_0'].geometry} material={materials['vray_dark-green']} />
      <mesh geometry={nodes['AduRFaSdUzdWigL_vray_dark-green_0'].geometry} material={materials['vray_dark-green']} />
    </group>
  )
}

export default DemoComputer
